-- 001_create_employee.sql
-- Employee table (dimension)
CREATE TABLE IF NOT EXISTS employee (
    client_employee_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    last_name VARCHAR(255) NOT NULL,
    preferred_name VARCHAR(255),
    job_code INT,
    job_title VARCHAR(255),
    job_start_date DATE,
    organization_id VARCHAR(100),
    organization_name VARCHAR(255),
    department_id VARCHAR(100),
    department_name VARCHAR(255),
    dob DATE,
    hire_date DATE NOT NULL,
    recent_hire_date DATE,
    anniversary_date DATE,
    term_date DATE,
    years_of_experience INT CHECK (years_of_experience >= 0),
    work_email VARCHAR(255) UNIQUE,
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip VARCHAR(50),
    country VARCHAR(100),
    manager_employee_id VARCHAR(50),
    manager_employee_name VARCHAR(255),
    fte_status VARCHAR(100),
    is_per_deim VARCHAR(100),
    cell_phone VARCHAR(50),
    work_phone VARCHAR(50),
    scheduled_weekly_hour INT CHECK (scheduled_weekly_hour >= 0),
    active_status INT CHECK (active_status IN (0,1)),
    termination_reason VARCHAR(255),
    clinical_level VARCHAR(255)
);