-- 005_create_staging_tables.sql
CREATE TABLE IF NOT EXISTS staging_employee (
    client_employee_id VARCHAR(50),
    first_name VARCHAR(512),
    middle_name VARCHAR(512),
    last_name VARCHAR(512),
    preferred_name VARCHAR(512),
    job_code INT,
    job_title VARCHAR(512),
    job_start_date DATE,
    organization_id VARCHAR(512),
    organization_name VARCHAR(512),
    department_id VARCHAR(512),
    department_name VARCHAR(512),
    dob DATE,
    hire_date DATE,
    recent_hire_date DATE,
    anniversary_date DATE,
    term_date DATE,
    years_of_experience INT,
    work_email VARCHAR(512),
    address VARCHAR(512),
    city VARCHAR(512),
    state VARCHAR(512),
    zip VARCHAR(512),
    country VARCHAR(512),
    manager_employee_id VARCHAR(50),
    manager_employee_name VARCHAR(512),
    fte_status VARCHAR(512),
    is_per_deim VARCHAR(512),
    cell_phone VARCHAR(512),
    work_phone VARCHAR(512),
    scheduled_weekly_hour INT,
    active_status INT,
    termination_reason VARCHAR(512),
    clinical_level VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS staging_timesheet (
    client_employee_id VARCHAR(50),
    department_id VARCHAR(512),
    department_name VARCHAR(512),
    home_department_id VARCHAR(512),
    home_department_name VARCHAR(512),
    pay_code VARCHAR(512),
    punch_in_comment VARCHAR(512),
    punch_out_comment VARCHAR(512),
    hours_worked NUMERIC,
    punch_apply_date DATE,
    punch_in_datetime TIMESTAMP,
    punch_out_datetime TIMESTAMP,
    scheduled_start_datetime TIMESTAMP,
    scheduled_end_datetime TIMESTAMP
);